### ISSUE TITLE
Myyjä voi tulostaa kerralla kaikki myymättömät liput.

### ISSUE THREAD

**Issue by sirkian** [sirkian/TicketGuru#18]
## Tarkempi kuvaus:
Järjestelmä generoi kaikki myymättömät liput tulostettavaksi ennakkomyynnin loputtua.

## Konteksti:
Suora lainaus **Tuoteomistajan terveisistä**: "Lipunmyyntipisteessä lipunmyyjä myy ja tulostaa asiakkaalle liput. Ennakkomyynnin loputtua loput liput tulostetaan ovella myytäviksi."

## Jotta:
- Loput liput voidaan myydä ovella.

## Todentaminen ja testaus:
- Luodaan testitapahtuma, tulostetaan kaikki liput. Varmennetaan, että liput generoituivat oikein, sekä lippujen määrä on oikea.

**Comment by koskinene** [comment]
[d7c3824](https://github.com/sirkian/ticketguru-client/commit/d7c382415a03209a7410899a97ca5b6bea5b4c6a)
