### ISSUE TITLE
Myyjä voi etsiä tiettyä tapahtumaa hakusanalla.

### ISSUE THREAD

**Issue by sirkian** [sirkian/TicketGuru#20]
## TODO:
 - [x] #69
 - [x] Rajapinnan testaus
 - [x] Käyttöliittymä tapahtuman hakemiselle
 - [x] Käyttöliittymän testaus
 - to be continued

## Tarkempi kuvaus:
Toteutetaan hakumahdollisuus ainakin tapahtuman nimen ja ~~kaupungin~~ tapahtumapaikan perusteella.

## Jotta:
- Tapahtuman etsintä nopeutuu.

## Todentaminen ja testaus:
- Luodaan testitapahtuma ja etsitään sitä nimen perusteella. Varmennetaan, että tapahtuma löytyy.
- ~~Luodaan testitapahtuma ja etsitään sitä paikkakunnan perusteella. Varmennetaan, että tapahtuma löytyy.~~
- Luodaan testitapahtumia ja etsitään niitä tapahtumapaikan nimen perusteella. Varmennetaan, että tapahtuma löytyy.

**Comment by koskinene** [comment]
93482af Frontti tehty
ec0a528 Back muokattu
