### ISSUE TITLE
Lipuntarkastajan pitää voida merkitä lippu käytetyksi

### ISSUE THREAD

**Issue by sirkian** [sirkian/TicketGuru#39]
## Tarkempi kuvaus:
Tarkastajan pitää siis voida syöttää koodi järjestelmään, jolloin järjestelmä todentaa että lippu on ostettu ja käyttämätön. 
Tarkastaja voi merkata lipun käytetyksi.

## Jotta:
- Samaa lippua ei voi käyttää kuin kerran.
- Lippujen väärentäminen ei ole mahdollista.

## Konteksti:
"Lipuissa on ovella helposti tarkastettava koodi, jolla lippu voidaan ovella merkitä käytetyksi."

**Comment by koskinene** [comment]
93efdd6 tehty
