### ISSUE TITLE
Pääkäyttäjä voi lisätä tapahtumapaikan järjestelmään

### ISSUE THREAD

**Issue by sirkian** [sirkian/TicketGuru#55]
## TODO:
 - [x] #65
 - [x] Rajapinnan testaus
 - [x] Postinumeron lisäys
 - [x] Käyttöliittymä tapahtumapaikan lisäämiselle
 - [x] Käyttäjän syöttämien tietojen validointi
 - [x] Käyttöliittymän testaus
 - to be continued

## Jotta
...jotta saadaan tapahtumapaikkoja järjestelmään. 

**Tapahtumapaikka-rajapinta olisi varmaan hyvä toteuttaa ennen tapahtuma-rajapintaa.**

**Comment by koskinene** [comment]
d5b8e1b postinumeron lisäys

**Comment by koskinene** [comment]
[265a3c3](https://github.com/sirkian/ticketguru-client/commit/265a3c3a2f1c41ce4b3e4f781b2184fdbdc04446) Tapahtumapaikan lisäys

**Comment by koskinene** [comment]
https://github.com/sirkian/ticketguru-client/commit/4c631d6f0ebacacbbd0f0ba695874c992a14c18f Validoinnit OK
