### ISSUE TITLE
Pääkäyttäjä voi muokata tapahtumapaikkaa

### ISSUE THREAD

**Issue by sirkian** [sirkian/TicketGuru#56]
## TODO:
 - [x] #64
 - [x] Rajapinnan testaus
 - [x] Käyttöliittymä tapahtumapaikan muokkaamiselle
 - [x] Käyttöliittymän testaus
 - to be continued

## Jotta
Luonnollisesti.

**Ei niin akuutti, mutta nice to have**

**Comment by koskinene** [comment]
[6b15060](https://github.com/sirkian/ticketguru-client/commit/6b15060aa93a1831ee2382a3336b0bb811a03e3d) tehty
