### ISSUE TITLE
Pääkäyttäjä voi poistaa tapahtumapaikan

### ISSUE THREAD

**Issue by sirkian** [sirkian/TicketGuru#57]
## TODO:
 - [x] #70
 - [x] Rajapinnan testaus
 - [x] Käyttöliittymä tapahtumapaikan poistamiselle
 - [x] Käyttöliittymän testaus
 - to be continued

## Jotta
Ihan vaan, että tarjotaan se CRUD.

**Comment by koskinene** [comment]
[49afc8d](https://github.com/sirkian/ticketguru-client/commit/49afc8dc2930d05e9614416aca10aa29c88f49b1) tehty
